config/routes.rb
Base::Application.routes.draw do
  get "password_resets/create"

  get "password_resets/edit"

  get "password_resets/update"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  
  get "signup_estud" => "estud_registro#new", :as => "signup_estud"
  
  
  get "cursosrealizados_menu_principal_profesor" => "cursosrealizados#menu_principal_profesor", :as => "cursosrealizados_menu_principal_profesor"
  get "secretariasis_menu_principal_secretaria" => "secretariasis#menu_principal_secretaria", :as => "secretariasis_menu_principal_secretaria"
  get "buscar_distributivos" => "secretariasis#result_busqueda", :as => "buscar_distributivos" 
  
  get "secretarias_menu_principal_secretaria" => "secretarias#menu_principal_secretaria", :as => "secretarias_menu_principal_secretaria"
  
  get "buscar_mallas" => "secretariasis#result_busquedamalla", :as => "buscar_mallas"
  get "buscar_estudiantes" => "secretariasis#result_estud", :as => "buscar_estudiantes"
  get "estudiantes_curso" => "secretariasis#estudiantes_curso", :as => "estudiantes_curso"
  
  get "estudiantes_estado" => "secretariasis#estudiantes_estado", :as => "estudiantes_estado"
  get "buscar_estado" => "secretariasis#result_estud_estado", :as => "buscar_estado"
  
  get "mallacurriculares_validar" => "mallacurriculares#create", :as => "mallacurriculares_validar"
  post "mallacurriculares_validar" => "mallacurriculares#create", :as => "mallacurriculares_validar"
  
  
  get "result_buscar" => "secretariasis#buscar", :as => "result_buscar"
  get "activar" => "secretariasis#activar", :as => "activar"
  get "validar" => "secretariasis#validar", :as => "validar"
  get "edit_matr_alum" => "secretariasis#edit_matr_alum", :as => "edit_matr_alum"
  get "update_matr_alum" => "secretariasis#update_matr_alum", :as => "update_matr_alum"
  get "historial" => "secretariasis#historial", :as => "historial"
  get "homologacion_notas" => "secretariasis#homologacion_notas", :as => "homologacion_notas"
  get "matricula_secre" => "secretariasis#matricula_secre", :as => "matricula_secre"
  get "matr_alum" => "secretariasis#matr_alum", :as => "matr_alum"
  get "edit_historial" => "secretariasis#edit_historial", :as => "edit_historial"
  get "update_notas_alum" => "secretariasis#update_notas_alum", :as => "update_notas_alum"
  get "update_niveles_secre" => "secretariasis#update_niveles", :as => "update_niveles_secre"
  get "update_cursos_secre" => "secretariasis#update_cursos", :as => "update_cursos_secre"
  get "update_homo" => "secretariasis#update_homo", :as => "update_homo"
  
  
  
  
  
   get "matriculasacademicas_menu_principal_alumno" => "matriculasacademicas#menu_principal_alumno", :as => "matriculasacademicas_menu_principal_alumno"
   
  
   get "index_menu_principal_admin" => "index#menu_principal_admin", :as => "index_menu_principal_admin"
  
  
  get "asignaturas_menu_principal_admin" => "asignaturas#menu_principal_admin", :as => "asignaturas_menu_principal_admin"
  get "asignaturas_menu_principal_admin_index" => "asignaturas#menu_principal_admin_index", :as => "asignaturas_menu_principal_admin_index"
  get "asignaturas_edit" => "asignaturas#menu_principal_admin_edit", :as => "asignaturas_menu_principal_admin_edit"
      
  
  get "secciones_menu_principal_admin" => "secciones#menu_principal_admin", :as => "secciones_menu_principal_admin"
  get "secciones_edit" => "secciones#menu_principal_admin_edit", :as => "secciones_menu_principal_admin_edit" 
  
  
  get "sessions_new" => "sessions#new", :as => "sessions_new"
  
  
   
  get "lectivos_menu_principal_admin" => "lectivos#menu_principal_admin", :as => "lectivos_menu_principal_admin"   
  get "niveles_menu_principal_admin" => "niveles#menu_principal_admin", :as => "niveles_menu_principal_admin"   
  get "tipomallas_menu_principal_admin" => "tipomallas#menu_principal_admin", :as => "tipomallas_menu_principal_admin"  
  get "mallacurriculares_menu_principal_admin" => "mallacurriculares#menu_principal_admin", :as => "mallacurriculares_menu_principal_admin"
  
  get "tiponiveles_menu_principal_admin" => "tiponiveles#menu_principal_admin", :as => "tiponiveles_menu_principal_admin"
    
  get "paralelos_menu_principal_admin" => "paralelos#menu_principal_admin", :as => "paralelos_menu_principal_admin"
  
  get "promotions_menu_principal_admin" => "promotions#menu_principal_admin", :as => "promotions_menu_principal_admin"  
  
  get "malla_asignar" => "mallacurriculares#asignar", :as => "malla_asignar"
  get "malla_eliminar" => "mallacurriculares#destroy", :as => "malla_eliminar"
        
  get "asignaturas/index"
  get "asignaturas/edit" 
  get "asignaturas/show" 

  get "secciones/index"
  get "secciones/edit" 
  get "secciones/show" 
  
  get "lectivos/index"
  get "lectivos/edit" 
  get "lectivos/show" 
  
  
  get "niveles/index"
  get "niveles/edit" 
  get "niveles/show"
  get "niveles/new"
  get "niveles/create"
      
  get "cursosrealizados/index"
  get "cursosrealizados/new"
  get "cursosrealizados/edit" 
  get "cursosrealizados/show"
  get "cursosrealizados/horario"
  
  
  get "secretarias/curriculsecretari"
  get "secretarias/new"
  get "secretarias/edit" 
  get "secretarias/show"       
  
  get "tipomallas/index"
  get "tipomallas/edit" 
  get "tipomallas/show"
  
  get "mallacurriculares/index"
  get "mallacurriculares/edit" 
  get "mallacurriculares/show"
  get "mallacurriculares/new"
  get "mallacurriculares/create"
  get "mallacurriculares/update"
  
  get "tiponiveles/index"
  get "tiponiveles/edit" 
  get "tiponiveles/show"
  
  get "paralelos/index"
  get "paralelos/edit" 
  get "paralelos/new"
  get "paralelos/update"
  get "paralelos_index" => "paralelos#index", :as => "paralelos_index"
  
  get "datosalumnos/index" 
  get "datosalumnos/edit"
  
  get "promotions/index"
  get "promotions/edit" 
  get "promotions/new"
  
  get "distributos/index"
  get "distributos/update"
  get "distributos/edit" 
  get "distributos/new"
  get "distributos/update_niveles", :as => "update_niveles"
  get "distributos/update_asignaturas", :as => "update_asignaturas"
  get "distributos/update_cursos", :as => "update_cursos"
  get "distributos_new" => "distributos#new", :as => "distributos_new"
  get "distributos_index" => "distributos#index", :as => "distributos_index"  
  get "distributos_menu_principal_admin" => "distributos#menu_principal_admin", :as => "distributos_menu_principal_admin"
  
  post "mallactual" => "mallacurriculares#update", :as => "mallactual"
  post "datoseditalum" => "datosalumnos#update", :as => "datoseditalum"
  post "datoseditalum" => "datosalumnos#update", :as => "datoseditalum"
  
  
  
  

  get "matriculasacademicas_imprimir" => "matriculasacademicas#imprimir", :as => "matriculasacademicas_imprimir" 
  get "matriculasacademicas_new" => "matriculasacademicas#new", :as => "matriculasacademicas_new"   
  
  get "matriculasacademicas/new"
  get "matriculasacademicas/index"
  get "matriculasacademicas/show"  
  
  get "notasasacademicas/new"
  get "notasacademicas/index"
  get "notasacademicas/estadistica"
  get "notasasacademicas/consultas_correo"  
  
  get "cursosprofesores/new"
  get "cursosprofesores/index"
  get "cursosprofesores/show"
  get "cursosprofesores/alumnos"
  get "cursosprofesores/edit"
  get "cursosprofesores/update"
  get "cursosprofesores/lista"
    
  get "alumnos_matriculados_lista" => "cursosprofesores#imprimir_lista", :as => "alumnos_matriculados_lista"
  
  get "alumnos_matriculados" => "cursosprofesores#new", :as => "alumnos_matriculados"
  get "edit_alumnos_matriculados" => "cursosprofesores#edit", :as => "edit_alumnos_matriculados"
  post "update_alumnos_matriculados" => "cursosprofesores#update", :as => "update_alumnos_matriculados"
  

  resources :users
  resources :sessions
  resources :asignaturas  
  resources :secciones
  resources :lectivos
  resources :niveles

  resources :personas
  
  resources :cursosrealizados
  resources :secretarias
  resources :tipomallas
  resources :tiponiveles
  resources :mallacurriculares
  resources :paralelos
  resources :promotions
  resources :distributos
  resources :cursosprofesores
  
  resources :notasacademicas
    
  resources :password_resets
  resources :secretrariasis
  
  

  
   root :to => 'index#menu_principal'

  match ':controller(/:action(/:id))(.:format)'
  match '/asignaturas/:id', :to => 'asignaturas#show', :as => :asignatura 
  match '/secciones/:id', :to => 'secciones#show', :as => :seccion
  match '/lectivos/:id', :to => 'lectivos#show', :as => :periodo 
  match '/niveles/:id', :to => 'niveles#show', :as => :nivel
      
  match '/cursosrealizados/:id', :to => 'cursosrealizados#edit', :as => :estudio
  match '/cursosrealizados/:id', :to => 'cursosrealizados#edit', :as => :laboral
  
  
  match '/tipomallas/:id', :to => 'tipomallas#show', :as => :clase
  match '/tiponiveles/:id', :to => 'tiponiveles#show', :as => :nivele
  match '/mallacurriculares/:id', :to => 'mallacurriculares#show', :as => :malla
  match '/paralelos/:id', :to => 'paralelos#show', :as => :curso

  match '/distributos/:id', :to => 'distributos#show', :as => :distributivo
  match '/users/:id', :to => 'users#index', :as => :user
  match '/matriculasacademicas/:id', :to => 'matriculasacademicas#show', :as => :matricula
  match '/cursosprofesores/:id', :to => 'cursosprofesores#show', :as => :calificacione
  
  match '/secretarias/:id', :to => 'secretarias#result_busquedaestud', :as => :persona
end

app/controllers/cursosrealizados_controller.rb
class CursosrealizadosController < ApplicationController
#   before_filter :require_login, :only => [:new, :edit, :destroy, :show, :index]
#   load_and_authorize_resource :only => [:new, :edit, :destroy] CON ESTO DIGO QUE "NO PUEDE VER EL CONTENIDO"
   before_filter :require_login, :only => [:new, :edit, :destroy, :show, :index]
#   before_filter :authenticated_prof
   #skip_
  
  def index 
    @estudio = Estudio.where(:persona_id => current_user.persona.id)
    @laboral = Laboral.where(:persona_id => current_user.persona.id)    
  end
    
  
  def error
    
  end
  
   
  def new
    @estudio= Estudio.new
    @laboral= Laboral.new
  end
  
  

  
  def horario
  @periodo_actual = Periodo.order("period_fech_ini").last()
# @niveles = Nivel.joins(:cursos => :distributivos).where(:distributivos => {:persona_id => current_user.persona.id, :periodos => {:id => @periodo_actual.id}}).select("DISTINCT(nivel_numero)")   
      
    
# @niveles = Nivel.joins(:asignaturas => {:distributivos => { :curso => :periodo}}).where(:periodos => {:id => @periodo_actual.id}).select("DISTINCT(nivel_numero)")
    

#      @asignaturas = Distributivo.where(:persona_id => current_user.persona.id).select("DISTINCT(distr_horarioa),(asig_nombre)")
#      @asignaturas = Asignatura.joins(:distributivos).where(:distributivos => {:persona_id => current_user.persona.id}).uniq     
  #@niveles = Nivel.joins(:cursos => :distributivos).where(:distributivos => {:persona_id => current_user.persona.id}).select("DISTINCT(nivel_numero)")
    
    
  #@asignaturas = Asignatura.joins(:distributivos =>{:curso => :periodo}).where(:periodos => {:id => @periodo_actual.id}).select("DISTINCT(asig_nombre)")
  @distributivo = Distributivo.joins(:curso => :periodo).where(:persona_id => current_user.persona.id, :periodos => {:id => @periodo_actual.id})#.select("DISTINCT(distr_horarioa),(distr_horariob)")
  end
  
  

      
  
  def create                                
    @estudio = Estudio.new(params[:estudio])
    @laboral = Laboral.new(params[:laboral])              
     
    @laboral.persona_id = current_user.persona.id
    @estudio.persona_id = current_user.persona.id
            
    if @estudio.save and @laboral.save
    redirect_to cursosrealizados_menu_principal_profesor_path,  :notice => 'CURRICULUM CREADO'   
    else
    render :new
    end
  end
  
    def lista
     @distributivo = Distributivo.where(:persona_id => current_user.persona.id)
    end
    
    
    
      def imprimir_lista
        @distributivo = Distributivo.find(params[:distr_id])
        @alumnos = Persona.joins(:matriculas => :curso).where(:matriculas => {:curso_id => @distributivo.curso_id})
     
        @alumnos_count = Persona.joins(:matriculas => :curso).where(:matriculas => {:curso_id => @distributivo.curso_id}).count()
        @matricula = Matricula.where(:persona_id => @alumnos)
      end
  
      
   
  
    def show 
    @estudios = Estudio.find(params[:id])
    @laborals = Laboral.find(params[:id])
    end
   
   
       
   def edit 
     @estudios = Estudio.find(params[:id])
     @laborals = Laboral.find(params[:id])     
     if @estudios.persona.id and @laborals.persona.id == current_user.persona_id
     
     else
     
      :render_404  
     
       
       if @estudios.id.present? and @laborals.id.present?
       
       flash[:error] = ""
       redirect_to cursosrealizados_menu_principal_profesor_path
     end         
   end
   end
   
#render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false MUESTRA MENSAJE DE ERROR DE URL INCORRECTA      
#    modelo = Modelo.find(params[:id]) rescue nil
#    redirect_to root_path if modelo.nil?
   
    
   
   
  def update
     if current_user.has_role? :profesor
     @estudio= Estudio.find (params[:id])
     @estudio.update_attributes(params[:estudio])
     @laboral= Laboral.find (params[:id])
     @laboral.update_attributes(params[:laboral])
     redirect_to cursosrealizados_menu_principal_profesor_path,  :notice => 'CURRICULUM ACTUALIZADO'  
     
     else
     @estudio= Estudio.find (params[:id])
     @estudio.update_attributes(params[:estudio])
     @laboral= Laboral.find (params[:id])
     @laboral.update_attributes(params[:laboral])
     redirect_to secretarias_menu_principal_secretaria_path,  :notice => 'CURRICULUM ACTUALIZADO'
   end
  end
   
   
end

app/helpers/cursosrealizados_helper.rb
module CursosrealizadosHelper
end

app/views/cursosrealizados/create.erb
PRODUCTO CREADO CON EXITO !!!

app/views/cursosrealizados/edit.erb
<h1><center>EDITE SU CURRICULUM</center></h1>

<%=form_for @estudios do |f| %>
   
<table align="center"> 
  
<tr>
  <td align="center"><font color="1038FF" SIZE="3"> NIVELES</font> </td>
  <td align="center"><font color="1038FF" SIZE="3"> INSTITUTOS QUE HA ESTUDIADO</font> </td>
  <td align="center"><font color="1038FF" SIZE="3"> TITULOS </font></td>
  <td align="center"><font color="1038FF" SIZE="3"> EXPERIENCIA LABORAL </font></td>
</tr>
  
  
  
 <tr> 
<FONT color ="#2A6913"  SIZE="3" FACE="arial">  
  <td><%=f.text_area :est_nivel, :rows => 10, :cols => 16 %></td>
  <td><%=f.text_area :est_instituto, :rows => 15, :cols => 36 %></td>  
  <td><%=f.text_area :est_titulos, :rows => 10, :cols => 16 %></td>
</FONT>


 
<%= form_for @laborals do |f| %>          
        <FONT color ="#2A6913"  SIZE="3" FACE="arial">            
          <td><%= f.text_area :rel_lab_inst_nomb, :rows => 15, :cols => 36 %></td>
        </FONT>
 </table>


<center><table><td><%=  f.submit "GUARDAR CURRICULUM", {:style => 'color: #C31B1B'} %></td></table></center>
<%end%>                                                   
 </tr>      
<%end%>

app/views/cursosrealizados/errors.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "errors" %>

app/views/cursosrealizados/index.erb
<html>                           
  <head>
    <script type="text/javascript" src="../scripts/javascript.js"></script>    
  </head>  
  <body>       
    <div id="pagina" style="background-image: url(/assets/popis111.jpg); height: 506px; width: 1300px; border: 1px solid black;">          
      
      
<h1><center>CURRICULUM</center></h1>
<% @estudio.each do |f| %>         
  <table align="center">        
    
    <tr>
      <td align="center"><font color="1038FF" SIZE="3"><b>NIVELES</b></font></td>
      <td align="center"><font color="1038FF" SIZE="3"><b>INSTITUTOS</b></font></td>
      <td align="center"><font color="1038FF" SIZE="3"><b>TITULOS OBTENIDOS</b></font></td>
      <td align="center"><font color="1038FF" SIZE="3"><b>EXPERIENCIA LABORAL</b></font></td>
    </tr>


<td><FONT SIZE="2"><%=f.est_nivel %></FONT></td>
<td><FONT SIZE="2"><%=f.est_instituto %></FONT></td>
<td><FONT SIZE="2"><%=f.est_titulos %></FONT></td>

<%end%>  
 
<% @laboral.each do |f| %>
<td><FONT SIZE="2"><%=f.rel_lab_inst_nomb %></FONT></td>   

<tr>
<td align="center"><%= link_to "EDITAR CURRICULUM", edit_cursosrealizado_path(f) %></td>  
</tr>
</table>
 
<%end%>  

</div>
 </body>
 </html>

app/views/cursosrealizados/lista.erb
<H1><center><font color="#0932FF">VER NOMINA DE ESTUDIANTES QUE PERTENECE A CADA CURSO</font></center></H1>
<br>
 

  <% @distributivo.each do |f| %>
<table>
  <td><font color="#C50000">NIVEL</font><%= f.curso.nivel.nivel_numero %></td>
  <td><%= f.curso.nivel.nivele.tip_niv_nombre %></td>
  <td><font color="#C50000">PARALELO</font> <%= f.curso.cur_paralelo %></td>
  <td><%= f.asignatura.asig_nombre %></td>

  <td>  =>>>>>>><%= link_to "VER NÓMINA DE ESTUDIANTES", alumnos_matriculados_lista_path(:distr_id => f.id), {:style => 'color: #0400FF'} %></td>  
  <br/>
</table>
<%end%>

app/views/cursosrealizados/menu_principal_profesor.erb
<html>
<head>
<%#=javascript_include_tag 'cycle.js'%>
<%#=stylesheet_link_tag 'index.css', :media => "screen" %>
<%#*<script type="text/javascript">$('#rotator').cycle('fade');%>
</script>
<title>AJAX: actualizar contenido</title>
<link href="style.css" rel="stylesheet" type="text/css" />
<link href="index.scss" rel="stylesheet" type="text/css" />
<script language="JavaScript" type="text/javascript" src="ajax.js"></script>
</head>    
       <head>         
         <style>
<!--
.styling{
background-color:black;
color:lime;
font: bold 16px MS Sans Serif;
padding: 3px;
}
-->
</style>         
       </head>       
       <body id="reloj">         
         <span id="digitalclock" class="styling"></span>
<script>
  
<!--
//HORA DEL SISTEMA EN VIVO
var alternate=0
var standardbrowser=!document.all&&!document.getElementById

if (standardbrowser)
document.write('<form name="tick"><input type="text" name="tock" size="11"></form>')

function show(){
if (!standardbrowser)
var clockobj=document.getElementById? document.getElementById("digitalclock") : document.all.digitalclock
var Digital=new Date()
var hours=Digital.getHours()
var minutes=Digital.getMinutes()
var dn="AM"

if (hours==12) dn="PM" 
if (hours>12){
dn="PM"
hours=hours-12
}
if (hours==0) hours=12
if (hours.toString().length==1)
hours="0"+hours
if (minutes<=9)
minutes="0"+minutes

if (standardbrowser){
if (alternate==0)
document.tick.tock.value=hours+" : "+minutes+" "+dn
else
document.tick.tock.value=hours+"   "+minutes+" "+dn
}
else{
if (alternate==0)
clockobj.innerHTML=hours+" : "+minutes+" "+"<sup style='font-size:1px'>"+dn+"</sup>"
else
clockobj.innerHTML=hours+" : "+minutes+" "+"<sup style='font-size:1px'>"+dn+"</sup>"
}
alternate=(alternate==0)? 1 : 0
setTimeout("show()",1000)
}
window.onload=show
//-->
</script>
         
         
         <script language="JavaScript">
<!--
// ==============================================
// FECHA MES, DIA, AÑO
var TheFontFace  = "algerian";
var TheFontColor = "#1656C4";
var TheFontSize  = "4";
var TheFontStyle = "boldcastellar"; 

// Set the separator between the date elements;
// usually use either - or /.

var TheSeparator = "-";

// Show or do not show the day of the week; set
// yes to show, no not to show.

var ShowDay ="yes";
// Do Not Edit Below This Line
// ==============================================
var Days = new Array("Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sabado");
var TheDate = new Date();

var TheWeekDay = TheDate.getDay();
var Day ="";
if (ShowDay == "yes"){
    Day = Days[TheWeekDay];
    Day += " ";}

var TheMonth = TheDate.getMonth() + 1;
if (TheMonth < 10) TheMonth = "0" + TheMonth;

var TheMonthDay = TheDate.getDate();
if (TheMonthDay < 10) TheMonthDay = "0" + TheMonthDay;

var TheYear = TheDate.getYear();
if (TheYear < 1000) TheYear += 1900;

var FontTagLeft  = "";
var FontTagRight = "";

if (TheFontStyle == "bold"){
    FontTagLeft = "<b>";
    FontTagRight ="</b>";}
    
if (TheFontStyle == "castellar"){
    FontTagLeft = "<i>";
    FontTagRight ="</i>";}
    
if (TheFontStyle == "boldcastellar"){
    FontTagLeft = "<b><i>"; 
    FontTagRight = "</i></b>";}    

var D = "";
D += "<font color='"+TheFontColor+"' face='"+TheFontFace+"' size='"+TheFontSize+"'>";
D += FontTagLeft+Day+TheMonth+TheSeparator+TheMonthDay+TheSeparator+TheYear+FontTagRight;
D += "</font>";
document.write(D);
//-->
</script>        
</body>
       <%if current_user%>
       <div align="right">                
   <font color="#0073FF" FACE="arial">BIENVENID@ </font> <b><%= current_user.email%></b>
       </div>

       <%end%>

  <body id="body2">        
    <div align="left">                                 
<b><font color ="#D101DC" FACE="roman"></b></f>  
    </div>      
    
    <%if current_user%>
    <div align="right"> 
      <font FACE="roman" ><b><%= link_to "Cerrar Sesión", logout_path %></b></font>
    </div>
    <%end%>
    
    
    <%if current_user%>
    <%else%>
    <div align="right">
    <%= link_to "INICIE SESIÓN", login_path %>
    </div>
    <%end%>        
    <HR noshade size="8" width="100%">  

    
    
       

  <%if current_user%> 
  <%else%>
<div id ="rotator">
<img align="right" <%=image_tag "pa3.jpg"%></img>
<img align="right" <%=image_tag "pa4.jpg"%></img>
<img align="right" <%=image_tag "papin.jpeg"%></img>
<img align="right" <%=image_tag "an1.jpg"%></img>
<img align="right" <%=image_tag "an2.jpg"%></img>
<img align="right" <%=image_tag "an3.jpg"%></img>
<img align="right" <%=image_tag "an4.jpg"%></img>
<img align="right" <%=image_tag "an5.jpg"%></img>
<img align="right" <%=image_tag "an6.jpg"%></img>
<img align="right" <%=image_tag "an7.jpg"%></img>
<img align="right" <%=image_tag "an8.jpg"%></img>
<img align="right" <%=image_tag "an9.jpg"%></img>
<img align="right" <%=image_tag "an10.jpg"%></img>
<img align="right" <%=image_tag "an12.jpg"%></img>
<img align="right" <%=image_tag "an13.jpg"%></img>
<img align="right" <%=image_tag "an14.jpg"%></img>
<img align="right" <%=image_tag "an15.jpg"%></img>
</div>
     <%end%>  
 
    
    
    
    <div align="center">                                  
      <p><font color="#1C2ACB" SIZE="6" FACE="algerian"><b>UNIDAD EDUCATIVA PARTICULAR MIXTA</b></font> <font color="#230000" SIZE="6" FACE="algerian"><b>"JUAN PABLO II"</b></font></p>
    </div>               
    
  <ul id="navi">   
  
  <li><a href="#"><b><font FACE="LUCIDA CONSOLE" color="C13131" size="3">CURRICULUM</font></b></a>
   <ul>
        <%if @estudio.nil? and @laboral.nil? == current_user %>
                <li><a href="javascript:Solicitud('cursosrealizados/new.html','pagina')"><b>Crear Curriculum</b></a></li>
                <li><a href="javascript:Solicitud('cursosrealizados/index.html','pagina')"><b>Ver Curriculum</b></a></li>                                                                                   
                
       <%else%>
                <li><a href="javascript:Solicitud('cursosrealizados/index.html','pagina')"><b>Ver Curriculum</b></a></li>
       <%end%>
   </ul>
  </li>
   
  
  
  
 
  <li><a href="#"><font FACE="LUCIDA CONSOLE" color="C13131" size="3"><b>CURSOS</b></font></a>
                  <ul>
                    <li><a href="javascript:Solicitud('cursosprofesores/index.html','pagina')"><b><font face="arial">LISTAR CURSOS</font></b></a></li>
                    <li><a href="javascript:Solicitud('cursosprofesores/lista.html','pagina')"><b><font face="arial">LISTA DE ESTUDIANTES</font></b></a></li>                    
                  </ul>
  </li>
  
  
  
  
  
  
  <li><a href="#"><b><font FACE="LUCIDA CONSOLE" color="C13131" size="3">DISTRIBUTIVO</font></b></a>  
                <ul>
                    <li><a href="javascript:Solicitud('cursosrealizados/horario.html','pagina')"><b><font face="arial">HORARIO DE CLASES</font></b></a></li>    
                </ul>
  
  </li>
  </ul>   
   
   
   
   
   <div id="contenedor">
	<div id="navi">		
	</div>
	<div id="pagina"></div>
</div>
 </body>
  </html> 

app/views/cursosrealizados/show.erb
    <%= notice %>
<p>NIVELES---><%= @estudios.est_nivel %></p>
<p>INSTITUTOS---><%= @estudios.est_instituto %></p>
<H1>TITULOS OBTENIDOS---><%= @estudios.est_titulos %></H1>


<p>EXPERIENCIA LABORAL---><%= @laborals.rel_lab_inst_nomb %></p>